name: Create BigQuery Dataset on PR

on:
  pull_request:
    types: [opened]

jobs:
  create-bigquery-dataset:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Google Cloud credentials
        uses: google-github-actions/setup-gcloud@master
        with:
          project-id: your-project-id
          service-account-key-file: ${{ secrets.BQ_DROP_SCHEMA_ON_MERGE }}
      
      - name: Create BigQuery dataset
        run: |
          # Replace this with actual code to create the BigQuery dataset
          gcloud bigquery datasets create "dbt_cloud_pr_8545_${{ runner.uniqueId }}"