name: Create BigQuery Dataset on PR
on:
  pull_request:
    types: [opened]

jobs:
  create-bigquery-dataset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud credentials
        uses: google-github-actions/auth@v1
        with:
          # Replace 'YOUR_SERVICE_ACCOUNT_KEY_FILE' with the actual path to your service account key file.
          service_account_key_file: ${{ secrets.BQ_DROP_SCHEMA_ON_MERGE }}

      - name: Create BigQuery dataset
        env:
          BUCKET_NAME: "alexvspreadsheets"
          DATASET_NAME: "dbt_cloud_pr_8545_${{ runner.uniqueId }}"

        run: |
          gcloud auth activate-service-account --key-file ${{ secrets.BQ_DROP_SCHEMA_ON_MERGE }}
          gcloud config set project ${BUCKET_NAME}
          gcloud bigquery datasets create "${DATASET_NAME}"
