name: Create BigQuery Dataset on PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  create-bigquery-dataset:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Authenticate with Google Cloud
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.BQ_DROP_SCHEMA_ON_MERGE }}'

      # Step 3: Set up gcloud CLI
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: "alexvspreadsheets"

      # Step 4: Verify bq CLI availability
      - name: Verify bq CLI
        run: |
          echo "Verifying bq CLI availability..."
          bq --help || echo "bq CLI is not available. Please check your setup."

      # Step 5: Create a BigQuery dataset
      - name: Create BigQuery dataset
        env:
          PROJECT_ID: "alexvspreadsheets"
          DATASET_NAME: "dbt_cloud_pr_${{ github.event.pull_request.number }}_${{ github.run_id }}"
        run: |
          echo "Creating BigQuery dataset..."
          bq --location=US mk --dataset "${PROJECT_ID}:${DATASET_NAME}" || echo "Dataset may already exist."
