name: Upload to Cloud Storage

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    env:
      LOCAL_MODE: 'true'  # Set this to 'true' for local MinIO upload
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install boto3

      - name: Upload file to MinIO
        run: |
          python upload_to_gcs.py  # Replace with your actual Python script name
