name: Upload Changed Files to MinIO

on:
  push:
    branches:
      - main
    paths:
      - '**/*'  # Monitor all files

jobs:
  upload:
    runs-on: ubuntu-latest
    env:
      LOCAL_MODE: 'true'  # Set this to 'true' for local MinIO upload
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install boto3

      - name: Upload changed files to MinIO
        run: |
          python upload_to_gcs.py
